- id: ifttt_webhook_received
  alias: IFTT Webhook Received
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      mac: '{{ trigger.event.data.mac }}'
      dev_id: '{{ trigger.event.data.dev_id }}'
      host_name: '{{ trigger.event.data.host_name }}'
      location_name: '{{ trigger.event.data.location_name }}'
- id: wallmote_activate_day_scene
  alias: Wallmote activate day
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - entity_id: scene.day_3
    service: scene.turn_on
- id: wallmote_activate_evening_scene
  alias: Wallmote activate evening
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - entity_id: scene.evening_2
    service: scene.turn_on
- id: wallmote_activate_night_scene
  alias: Wallmote activate night
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: scene.night
    service: scene.turn_on
- id: wallmote_activate_test_scene
  alias: Wallmote activate away
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 4
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: scene.away_2
    service: scene.turn_on
- id: Nightlight
  alias: Nightlight
  trigger:
  - entity_id: binary_sensor.fibaro_long_hall_multisensor_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.long_hall_lights
    state: 'off'
  - after: '22:00:00'
    before: 06:39:00
    condition: time
  action:
  - data:
      entity_id: scene.nightlight_long_hall
    service: scene.turn_on
  - delay: 00:00:30
  - data:
      entity_id: light.long_hall_lights
    service: light.turn_off
  - service: script.long_hall_lights_of_when_no_brightnesschange
- id: opple_activate_day scene
  alias: OPPLE activate day scene
  trigger:
  - event_data:
      id: lumi_remote_b486opcn01_27
      event: 1002
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.day_3
    service: scene.turn_on
- id: opple_activate_evening_scene
  alias: OPPLE activate evening scene
  trigger:
  - event_data:
      id: lumi_remote_b486opcn01_27
      event: 2002
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.evening_2
    service: scene.turn_on
- id: opple_activate_night_scene
  alias: OPPLE activate night scene
  trigger:
  - event_data:
      id: lumi_remote_b486opcn01_27
      event: 3002
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.night
    service: scene.turn_on
- id: opple_activate_away_scene
  alias: OPPLE activate away scene
  trigger:
  - event_data:
      event: 4002
      id: lumi_remote_b486opcn01_27
    event_type: deconz_event
    platform: event
  #- event_data:
  #    event: 4002
  #    id: lumi_remote_2
  #  event_type: deconz_event
  #  platform: event
  condition: []
  action:
  - entity_id: scene.away_2
    service: scene.turn_on
  mode: single
