- id: '1547062417011'
  alias: Light on in the morning
  trigger:
  - entity_id: binary_sensor.motion_hall
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.dimmer_hall
    state: 'off'
  - after: 06:40:00
    before: 07:10:00
    condition: time
  action:
  - data:
      entity_id: scene.day
    service: scene.turn_on
- id: '1547062685731'
  alias: Nightlight
  trigger:
  - entity_id: binary_sensor.motion_hall
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.dimmer_hall
    state: 'off'
  - after: '22:00:00'
    before: 06:39:00
    condition: time
  action:
  - data:
      brightness: 28
      entity_id: binary_sensor.motion_hall
      transition: 2
    service: light.turn_on
  - delay: 00:00:30
  - data:
      entity_id: binary_sensor.motion_hall
    service: light.turn_off
- id: ifttt_webhook_received
  alias: IFTT Webhook Received
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      mac: '{{ trigger.event.data.mac }}'
      dev_id: '{{ trigger.event.data.dev_id }}'
      host_name: '{{ trigger.event.data.host_name }}'
      location_name: '{{ trigger.event.data.location_name }}'
- id: wallmote_activate_test_scene
  alias: Wallmote activate test scene
  trigger:
  - event_data:
      entity_id: switch.aeotec_wallmote_quad_1
      scene_data: '0'
      scene_id: '4'
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: scene.test
    service: scene.turn_on
