- id: ifttt_webhook_received
  alias: IFTT Webhook Received
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      mac: '{{ trigger.event.data.mac }}'
      dev_id: '{{ trigger.event.data.dev_id }}'
      host_name: '{{ trigger.event.data.host_name }}'
      location_name: '{{ trigger.event.data.location_name }}'
- id: wallmote_activate_day_scene
  alias: Wallmote activate day
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: scene.turn_on
      entity_id: scene.day_3
    - service: media_player.select_source    
      data: 
        entity_id: media_player.kjkken
        source: NRK P13 
- id: wallmote_activate_evening_scene
  alias: Wallmote activate evening
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - entity_id: scene.evening_2
    service: scene.turn_on
- id: wallmote_activate_night_scene
  alias: Wallmote activate night
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: scene.night
    service: scene.turn_on
- id: wallmote_activate_test_scene
  alias: Wallmote activate away
  trigger:
  - event_data:
      entity_id: zwave.aotec_multi_remote_quad
      scene_data: 0
      scene_id: 4
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: scene.away_2
    service: scene.turn_on
- id: Nightlight
  alias: Nightlight
  trigger:
  - entity_id: binary_sensor.fibaro_long_hall_multisensor_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.long_hall_lights
    state: 'off'
  - after: '21:00:00'
    before: 09:00:00
    condition: time
  action:
  - data:
      entity_id: scene.nightlight_long_hall
    service: scene.turn_on
  - delay: 00:00:30
#  - data:
#      entity_id: light.long_hall_lights
#    service: light.turn_off
  - service: script.long_hall_lights_of_when_no_brightnesschange
- id: opple_activate_day scene
  alias: OPPLE activate day scene
  trigger:
  - event_data:
      id: hall_scene_switch
      event: 1002
    event_type: deconz_event
    platform: event
  - event_data:
      event: 1002
      id: entrance_scene_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.day_3
    service: scene.turn_on
- id: opple_activate_evening_scene
  alias: OPPLE activate evening scene
  trigger:
  - event_data:
      id: hall_scene_switch
      event: 2002
    event_type: deconz_event
    platform: event
  - event_data:
      event: 2002
      id: entrance_scene_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.evening_2
    service: scene.turn_on
- id: opple_activate_night_scene
  alias: OPPLE activate night scene
  trigger:
  - event_data:
      id: hall_scene_switch
      event: 3002
    event_type: deconz_event
    platform: event
  - event_data:
      event: 3002
      id: entrance_scene_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.night
    service: scene.turn_on
- id: opple_activate_away_scene
  alias: OPPLE activate away scene
  trigger:
  - event_data:
      event: 4002
      id: hall_scene_switch
    event_type: deconz_event
    platform: event
  - event_data:
      event: 4002
      id: entrance_scene_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - entity_id: scene.away_2
    service: scene.turn_on
  mode: single

- id: cooling_room_door_is_left_open 
  alias: 'Notify if the cooling room door is left open'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.cooler_room_door
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.notify
    data_template:
      message: >
          The {{ trigger.to_state.attributes.friendly_name }} was left open

- id: test
  alias: "test"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_33
      gesture: 7      
  action:
#    - service: media_player.select_source    
#        entity_id: media_player.kjkken
#        source: NRK P13
    - service: system_log.write
      data:
        message: >
            dette er før 1
    - service: system_log.write
      data:
        message: >
            dette er etter 1
- id: cube_rotatel_left
  alias: "Cube rotate left"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_33
      gesture: 8      
  action:
#    - service: light.turn_on
#      data_template:
#        entity_id: light.stue_orange
#        brightness: >
#            {% set state = states.light.stue_orange.attributes.brightness + (trigger.event.data.event|float)/100 -%}
#            {%-  if state < 0 -%}
#               {%- set state  = 0 -%}
#            {%- endif %}
#            {{ state }}
    - service: system_log.write
      data:
        message: >
            {% if states.light.stue_orange.attributes.brightness < 0  %}
               0
            {% else %}
               states.light.stue_orange.attributes.brightness
            {% endif %}
           
