- id: Lights_on_in_the_morning_on_motion_weekdays
  alias: Lys på om morgenen ved bevegelse i ukedager
  trigger:
  - entity_id: binary_sensor.motion_hall
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.dimmer_hall
    state: 'off'
  - after: 08:30:00
    before: '09:00:00'
    condition: time
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - data:
      brightness: 150
      entity_id:
      - light.dimmer_hall
      - light.dimmer_diningtable
      - light.hjrnelampe
      transition: 10
    service: light.turn_on

- id: Lights_on_in_the_morning_on_motion_weekends
  alias: Lys på om morgenen ved bevegelse i helg
  trigger:
  - entity_id: binary_sensor.motion_hall
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.dimmer_hall
    state: 'off'
  - after: 08:30:00
    before: '09:00:00'
    condition: time
  - condition: time
    weekday:
      - sat
      - sun
  action:
  - data:
      brightness: 150
      entity_id:
      - light.dimmer_hall
      - light.dimmer_diningtable
      - light.hjrnelampe
      transition: 10
    service: light.turn_on
    
- id: Lights_on_in_the_night_on_motion
  alias: Lys av i gang etter 30 sekunder uten bevelgese
  trigger:
  - entity_id: binary_sensor.motion_hall
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.dimmer_hall
    state: 'off'
  - after: '22:00:00'
    before: 09:00:00
    condition: time
  action:
  - data:
      brightness: 28
      entity_id: light.dimmer_hall
      transition: 2
    service: light.turn_on
  - delay: 00:00:30
  - data:
      entity_id: light.dimmer_hall
    service: light.turn_off

- id: Close_garage_door_on_sundown
  alias: Lukk garasje ved solnedgang
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: garage_door.last_message
    state: Open
  action:
  - service: garage_door.trigger_door

- id: ifttt_webhook_received
  alias: IFTT Webhook Received
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
