homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret myLatitude
  longitude: !secret myLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 155
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml
  
lovelace:
  mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret apiPassword
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery: 
   #enable:
   # - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

# Enables a map showing the location of tracked devices
map:

mqtt:
  broker: !secret mqttBroker
  port: !secret mqttPort
  username: !secret mqttUser
  password: !secret mqttPassword

# Track the sun
sun:

# Connected garage door
garage_door:
  status_topic: /connectedGarageDoor/status

# Weather prediction
sensor:
  - platform: yr
    name: Været
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
  
  - platform: google_wifi
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

# Text to speech
tts:
  - platform: google

zwave:
  usb_path: /dev/ttyACM0
  
recorder:
  purge_keep_days: 14
  db_url: !secret mariadb_connection_url

# Cloud
cloud:

sonos:
  media_player:
    hosts:
      - 192.168.86.97
      - 192.168.86.42

ios:
apple_tv:
#  - host: 192.168.86.62
#    name: stua

tibber:
  access_token: !secret tibberToken

wunderlist:
  client_id: !secret wunderListClientId
  access_token: !secret wunderListToken
      
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
