
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

title: Casa Framstad
views:
  - title: Home
    path: home
    name: Hjem
    icon: mdi:home-circle
    cards: 
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: device_tracker.liv
                show_name: false
                show_state: false
                state_image:
                  "home": /local/people/liv.png
                  "not_home": /local/people/liv_away.png
              - type: picture-entity
                entity: device_tracker.kristoffer
                show_name: false
                show_state: false
                state_image:
                  "home": /local/people/stoffer.png
                  "not_home": /local/people/stoffer_away.png
              - type: picture-entity
                entity: device_tracker.knut
                show_name: false
                show_state: false
                state_image:
                  "home": /local/people/knut.png
                  "not_home": /local/people/knut_away.png
          #- type: horizontal-stack
          #  cards:
              - type: picture-entity
                entity: device_tracker.linus
                show_name: false
                show_state: false
                state_image:
                  "home": /local/people/linus.png
                  "not_home": /local/people/linus_away.png
              - type: picture-entity
                entity: device_tracker.sigurd
                show_name: false
                show_state: false
                state_image:
                  "home": /local/people/sigurd.png
                  "not_home": /local/people/sigurd_away.png
              #- type: picture-entity
              #  entity: device_tracker.wvwzzzauzgw912198
              #  show_name: false
              #  show_state: false
              #  state_image:
              #    "home": /local/people/egolf.png
              #    "not_home": /local/people/egolf_away.png
      
          - type: glance
            name: Scene
            show_name: true
            show_state: false
            entities:   
              - entity: scene.day
                show_name: false
                show_state: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.day"}
              - entity: scene.evening
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.evening"}
              - entity: scene.night
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.night"}
              - entity: scene.test
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.test"}
          - type: horizontal-stack
            cards:
              - type: glance
                name: Trikk fra Sæter
                entities:
                  - sensor.trikk_fra_ster_ster_platform_12349
                  - sensor.moon
                  - sensor.temprature_hall

          - type: custom:weather-card
            entity: weather.metno
          - type: map
            aspect_ratio: 16:9
            default_zoom: 15
            entities:
              - device_tracker.kristoffer_sin_iphone
              - device_tracker.linus_sin_iphone  
              - device_tracker.wvwzzzauzgw912198
 
  - title: Lys
    path: lys
    name: Lys
    panel: false
    icon: mdi:lightbulb-outline
    cards: 
      - type: vertical-stack
        cards:
          - type: glance
            name: Scene
            show_name: true
            show_state: false
            entities:   
              - entity: scene.day
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.day"}
              - entity: scene.evening
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.evening"}
              - entity: scene.night
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.night"}
              - entity: scene.test
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data: {"entity_id": "scene.test"}
          
          - type: entities
            entities:
              - light.dimmer_diningtable
              - light.kitchen_bench
              - light.dimmer_hall
              - light.hjrnelampe
          
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dimmer_diningtable
              - type: light
                entity: light.kitchen_bench
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dimmer_hall
              - type: light
                entity: light.hjrnelampe
          
          - type: history-graph
            title: Motion in hall
            entities:
              - binary_sensor.motion_hall
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temprature_hall
                name: Hall temprature      
                accuracy: 500
                detail: 2
                graph: line
              - type: sensor
                name: Outside temprature
                entity: sensor.vret_temperature
                accuracy: 500
                detail: 2
                graph: line  
    
  - title: Media
    path: Media
    icon: mdi:music-note
    cards: 
      - type: media-control
        entity: media_player.stue
      - type: media-control
        entity: media_player.kjkken
 
  - title: E-Golf
    path: car
    icon: mdi:car-connected
    cards: 
      - type: entities
        title: VW E-Golf
        entities:
          - sensor.wvwzzzauzgw912198_battery_level
          - switch.wvwzzzauzgw912198_charging
          - switch.wvwzzzauzgw912198_window_heater
          - switch.wvwzzzauzgw912198_climatisation
          - sensor.wvwzzzauzgw912198_charging_time_left
          - sensor.wvwzzzauzgw912198_odometer
          - sensor.wvwzzzauzgw912198_electric_range
          - sensor.wvwzzzauzgw912198_last_connected
          - sensor.wvwzzzauzgw912198_service_inspection
          - sensor.wvwzzzauzgw912198_climatisation_target_temperature
          - binary_sensor.wvwzzzauzgw912198_parking_light
          - binary_sensor.wvwzzzauzgw912198_external_power
          - binary_sensor.wvwzzzauzgw912198_climatisation_without_external_power
          - lock.wvwzzzauzgw912198_doors_locked
    
  - title: Info
    path: info
    icon: mdi:information-outline
    cards:
      - type: glance
        entities: 
          - sensor.kristoffer_sin_iphone_battery_level
          - sensor.kristoffer_sin_iphone_battery_state
          - sensor.linus_sin_iphone_battery_level
          - sensor.linus_sin_iphone_battery_state
      - type: glance
        title: Garasjen min
        entities:
          - garage_door.last_message
          - entity: script.garage_door_trigger
            tap_action:
              action: call-service
              service: script.turn_on
              service_data: {"entity_id": "script.garage_door_trigger"}
      - type: sensor
        entity: sensor.electricity_price_tyslevveien_59_f
        name: Strømpris
        accuracy: 500
        detail: 2
        graph: line
  
  - title: Settings
    path: Settings
    icon: mdi:settings
    cards:
      - type: vertical-stack
        cards: 
          - type: entities
            title: Z-wave
            entities: 
              - zwave.aeotec_zw090_zstick_gen5_eu
              - zwave.fibaro_system_fgd212_dimmer_2
              - zwave.fibaro_system_fgd212_dimmer_2_2
              - zwave.fibaro_system_fgms001zw5_motion_sensor
              - switch.aeotec_wallmote_quad_1
              - switch.aeotec_zw130_wallmote_quad_switch_2
              - switch.aeotec_zw130_wallmote_quad_switch_3
              - switch.aeotec_zw130_wallmote_quad_switch_4
              - switch.aeotec_zw130_wallmote_quad_switch_5
          - type: entities
            title: Google WiFi
            entities: 
              - sensor.speedtest_download
              - sensor.speedtest_ping
              - sensor.speedtest_upload
              - sensor.google_wifi_current_version
              - sensor.google_wifi_last_restart
              - sensor.google_wifi_local_ip
              - sensor.google_wifi_new_version
              - sensor.google_wifi_status
              - sensor.google_wifi_uptime


      

