title: Casa Framstad
views:
  - title: Lys
    path: lys
    name: Lys
    panel: false
    icon: mdi:lightbulb-outline
  #- type: vertical-stack
    cards:  
      - type: entities
        name: Lys
        entities:
          - light.hjrnelampe
          - light.dimmer_diningtable
          - light.dimmer_hall
      - type: sensor
        entity: sensor.temprature_hall
        name: Temperatur      
        accuracy: 500
        detail: 2
        graph: line
      - type: sensor
        name: Utetempratur
        entity: sensor.vret_temperature
        accuracy: 500
        detail: 2
        graph: line
      - type: history-graph
        title: Bevegelse i gangen
        entities:
          - binary_sensor.motion_hall
 
  - title: Media
    path: Media
    icon: mdi:music-note
    cards: 
      - type: media-control
        entity: media_player.stue
      - type: media-control
        entity: media_player.kjkken
 
  - title: Info
    path: info
    icon: mdi:information-outline
    cards:
      - type: entities
        title: Vær fra YR.no
        entities:
          - sensor.vret_humidity
          - sensor.vret_precipitation
          - sensor.vret_pressure
          - sensor.vret_symbol
          - sensor.vret_temperature
          - sensor.vret_wind_direction
          - sensor.vret_wind_speed
          - sun.sun
      - type: entities
        title: Google WiFi
        entities: 
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
          - sensor.google_wifi_current_version
          - sensor.google_wifi_last_restart
          - sensor.google_wifi_local_ip
          - sensor.google_wifi_new_version
          - sensor.google_wifi_status
          - sensor.google_wifi_uptime
      - type: entities
        title: Garasjen min
        entities:
          - garage_door.last_message
          - script.garage_door_trigger
      - type: sensor
        entity: sensor.electricity_price_tyslevveien_59_f
        name: Strømpris
        accuracy: 500
        detail: 2
        graph: line
  - title: Settings
    path: Settings
    icon: mdi:settings
    cards:
      - type: entities
        title: Z-wave
        entities: 
          - zwave.aeotec_zw090_zstick_gen5_eu
          - zwave.fibaro_system_fgd212_dimmer_2
          - zwave.fibaro_system_fgd212_dimmer_2_2
          - zwave.fibaro_system_fgms001zw5_motion_sensor



      

